project:
  type: website
  output-dir: docs

website:
  title: "Lab Praktikum Departemen Matematika FMIPA UI"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - ./semuahalaman/about.qmd
      - ./semuahalaman/praktikum.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



